version: '3.8'

services:
  psql:
    image: postgres:latest
    environment:
      POSTGRES_DB: $postgres_db}
      POSTGRES_USER: ${zarokewinda}
      POSTGRES_PASSWORD: ${password}
    ports:
      - "${5432}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data

volumes:
  psql_volume: