DROP TABLE IF EXISTS Categories
DROP TABLE IF EXISTS Dishes
DROP TABLE IF EXISTS Ingredients
DROP TABLE IF EXISTS Dish_Ingredients
DROP TABLE IF EXISTS Menus
DROP TABLE IF EXISTS Menu_Dishes
DROP TABLE IF EXISTS Users